path:
  FILES_PATH: "./artifacts/files/"
  
embedding:
  batch_size: 40
  block_size: 200

GPT:
  dimension: 512
  nheads: 8
  dropout: 0.1
  num_layers: 6
  eps: 1e-05
  bias: True
  dim_feedforward: 2048
  activation: "gelu"